### ISSUE TITLE
Spent time Search Box

### ISSUE THREAD

**Issue by ballanz89** [farend/redmine_searchable_selectbox#10]
Does this work also on spent time Activity dropdown?

**Comment by ishikawa999** [comment]
@ballanz89 
> Does this work also on spent time Activity dropdown?

It works for Activity dropdown in my environment.
Is it different in your environment?
<img width="876" alt="screenshot 2021-01-21 8 33 45" src="https://user-images.githubusercontent.com/14245262/105253747-6cf9e980-5bc3-11eb-9428-e31aaab8ad89.png">

**Comment by ishikawa999** [comment]
Close because there is no reply.
Please reopen if necessary.
