### ISSUE TITLE
Width size problem

### ISSUE THREAD

**Issue by KinGsNowGH** [farend/redmine_searchable_selectbox#11]
Hi,
This plugin is essential and is a must to QoL, i'm only having some problems where the width is not the size correct therefore i cant read the options, as i show below:
![image](https://user-images.githubusercontent.com/61286068/111988219-f871f700-8aee-11eb-8d02-6b14a13d6365.png)

- After i select an option, it resizes correctly, as below:

![image](https://user-images.githubusercontent.com/61286068/111988278-12133e80-8aef-11eb-925d-4d6e2b9485d0.png)
![image](https://user-images.githubusercontent.com/61286068/111988304-1a6b7980-8aef-11eb-929f-3c5722642bd2.png)

- Gantt date experience the same problem:

![image](https://user-images.githubusercontent.com/61286068/111988386-340cc100-8aef-11eb-918b-f6f2cb43e404.png)

```
Environment:
  Redmine version                3.4.13.stable
  Ruby version                   2.3.8-p459 (2018-10-18) [x86_64-linux-gnu]
  Rails version                  4.2.11.1
  Environment                    production
  Database adapter               Mysql2
  Database timezone              -03
  ActiveRecord timezone          local
  App timezone                   UTC
SCM:
  Subversion                     1.9.3
  Darcs                          2.10.2
  Mercurial                      3.7.3
  Cvs                            1.12.13
  Bazaar                         2.7.0
  Git                            2.24.1
  Filesystem
```

**Comment by ishikawa999** [comment]
@KinGsNowGH 
Thanks for sharing the issue!

I think it has improved a little by making the change in https://github.com/farend/redmine_searchable_selectbox/commit/bb8aaedbe4486b9096878c882c6cf76a01a9f293.
If you want to make further changes, try rewriting the 100px part of https://github.com/farend/redmine_searchable_selectbox/commit/bb8aaedbe4486b9096878c882c6cf76a01a9f293 to your favorite value.

**Comment by ishikawa999** [comment]
This issue will be closed as we have fixed the layout collapse issue.
