### ISSUE TITLE
Installation on Redmine 5.0.1 fails

### ISSUE THREAD

**Issue by pasqualedante** [farend/redmine_searchable_selectbox#14]
Installation on Redmine 5.0.1 fails with the following error message:

App 7818 output: Error: The application encountered the following error: uninitialized constant SearchableSelectbox::Patches::MyHelperPatch (NameError)
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 7818 output: /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
App 7818 output: /opt/redmine/config/environment.rb:16:in `<top (required)>'
App 7818 output: config.ru:3:in `require'
App 7818 output: config.ru:3:in `block in <main>'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
App 7818 output: /opt/redmine/vendor/cache/ruby/3.0.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
App 7818 output: config.ru:1:in `new'
App 7818 output: config.ru:1:in `<main>'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:101:in `eval'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 7818 output: /usr/local/rvm/gems/ruby-3.0.0/gems/passenger-6.0.14/src/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2022-05-18 17:15:13.2203 7789/Tf age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: uninitialized constant SearchableSelectbox::Patches::MyHelperPatch (NameError)
Error ID: a4d78bde
Error details saved to: /tmp/passenger-error-Orc6Md.html

**Comment by ishikawa999** [comment]
@pasqualedante 
Could you tell us which version of redmine_searchable_selectbox you are using?
The latest redmine_searchable_selectbox is compatible with Redmine 5.0.1, so the plugin may be out of date.

**Comment by pasqualedante** [comment]
Hi @ishikawa999 , I have cloned the tip of this repo (release 0.1.9)

**Comment by ishikawa999** [comment]
@pasqualedante 

Thanks for the info.
Thanks to you I was able to reproduce the problem.

I have added the code for the fix in the [fix-14](https://github.com/farend/redmine_searchable_selectbox/pull/15/files) branch, could you please try it? If no problem, I will merge it into the master branch.

**Comment by pasqualedante** [comment]
Ciao @ishikawa999 for me r+ for your patches: it works, thanks!

**Comment by ishikawa999** [comment]
@pasqualedante 
Thank you!
