### ISSUE TITLE
redmineup plugins

### ISSUE THREAD

**Issue by ashrafalzyoud** [farend/redmine_searchable_selectbox#27]
its conflict with all redmineup the page up and down

**Comment by ashrafalzyoud** [comment]
@ishikawa999 
@vividtone

**Comment by vividtone** [comment]
We do not usually use RedmineUP plugins, so we have not verified compatibility with them. Therefore, we currently do not plan to fix the issue you reported.

**Comment by vividtone** [comment]
I am closing this issue.
